import type { PassportRecord } from './types';
import { EMPTY_PASSPORT } from './types';

// ============================================================
// Sample Passport Templates
// ============================================================

export interface SampleTemplate {
  id: string;
  label: string;
  description: string;
  data: Omit<PassportRecord, 'slug' | 'edit_token'>;
}

export const SAMPLE_TEMPLATES: SampleTemplate[] = [
  {
    id: 'organic-cotton-tee',
    label: 'Organic Cotton T-Shirt',
    description: 'A textile product with composition, care, and sustainability data.',
    data: {
      ...EMPTY_PASSPORT,
      brand_name: 'Loom & Field',
      product_name: 'Organic Cotton Everyday Tee',
      category: 'Textile / apparel',
      product_type: 'T-shirt',
      sku: 'LF-TEE-OC-001',
      model: 'Everyday Tee',
      product_category_module: 'textile',
      materials: '100% organic cotton jersey, GOTS certified',
      composition: '100% organic cotton',
      recycled_content: 'Not applicable (organic virgin cotton)',
      packaging_materials: 'Recycled paper mailer, compostable poly bag',
      country_of_origin: 'Portugal',
      production_country: 'Portugal',
      manufacturer_name: 'Fábrica Têxtil do Norte, Lda.',
      manufacturer_contact: 'info@loomandfield.com',
      care_instructions: 'Machine wash cold (30°C). Line dry. Do not bleach. Iron low heat.',
      safety_warnings: 'Keep away from open flame.',
      repair_info: 'Small holes can be repaired with cotton thread. Repair guide available on website.',
      recycling_info: 'Textile recycling available in most EU countries. Remove labels before recycling.',
      end_of_life_info: 'Return to brand takeback program for recycling credit.',
      takeback_info: 'Send to Loom & Field Circular Program for recycling.',
      warranty_info: '30-day policy for manufacturing defects.',
      support_email: 'hello@loomandfield.com',
      target_markets: ['EU', 'UK'],
      last_updated: new Date().toISOString().split('T')[0],
      textile_label_notes: 'Fibre composition: 100% organic cotton. Care labels included.',
      gpsr_notes: 'Manufacturer and contact information provided. Safety information included.',
      dpp_readiness_notes: 'Core DPP fields completed for textile product.',
    },
  },
  {
    id: 'leather-bag',
    label: 'Handmade Leather Bag',
    description: 'A leather goods product with material, care, and EUDR watch notes.',
    data: {
      ...EMPTY_PASSPORT,
      brand_name: 'Atelier North',
      product_name: 'Handmade Leather Crossbody Bag',
      category: 'Leather goods / accessories',
      product_type: 'Crossbody bag',
      sku: 'AN-BAG-CB-001',
      model: 'Crossbody Classic',
      product_category_module: 'leather_goods',
      materials: 'Vegetable-tanned leather (bovine), cotton twill lining, brass hardware',
      composition: 'Exterior: 100% bovine leather. Lining: 100% cotton. Hardware: brass.',
      country_of_origin: 'Spain',
      production_country: 'Spain',
      manufacturer_name: 'Taller Artesano de Ubrique',
      manufacturer_contact: 'contact@ateliernorth.com',
      care_instructions: 'Wipe with dry cloth. Condition leather every 3-6 months. Avoid prolonged moisture.',
      safety_warnings: 'Avoid prolonged moisture exposure. Metal hardware may tarnish.',
      repair_info: 'Strap and hardware repair available through brand. Contact for repair form.',
      recycling_info: 'Separate metal hardware before recycling leather where possible.',
      warranty_info: '1-year workmanship warranty. Does not cover normal wear.',
      support_email: 'care@ateliernorth.com',
      support_url: 'https://ateliernorth.com/care',
      target_markets: ['EU', 'UK', 'US'],
      last_updated: new Date().toISOString().split('T')[0],
      eudr_watch_notes: 'Bovine leather sourced from EU tannery. Monitor regulatory changes for cattle-related products.',
      gpsr_notes: 'Manufacturer information provided. Product does not contain known hazards.',
      dpp_readiness_notes: 'Core fields completed. EUDR watch flag added.',
    },
  },
  {
    id: 'wooden-stool',
    label: 'Wooden Stool',
    description: 'A furniture product with wood traceability and EUDR watch notes.',
    data: {
      ...EMPTY_PASSPORT,
      brand_name: 'Oak & Room',
      product_name: 'Solid Oak Utility Stool',
      category: 'Furniture / wood',
      product_type: 'Stool',
      sku: 'OR-STL-OAK-001',
      model: 'Utility Stool',
      product_category_module: 'furniture',
      materials: 'Solid European oak, water-based lacquer finish',
      composition: 'Frame: 100% European oak. Finish: water-based lacquer.',
      country_of_origin: 'Lithuania',
      production_country: 'Lithuania',
      manufacturer_name: 'Medžio Dirbtuvės UAB',
      manufacturer_contact: 'hello@oakandroom.com',
      care_instructions: 'Wipe with damp cloth. Avoid standing water. Do not use abrasive cleaners.',
      safety_warnings: 'Indoor use only. Maximum load: 120kg. Place on level surface.',
      repair_info: 'Sand and refinish if surface is damaged. Replacement parts available.',
      spare_parts_info: 'Replacement legs and seat available. Contact support.',
      durability_notes: 'Designed for 10+ years of daily use with proper care.',
      recycling_info: 'Wood is recyclable or reusable. Separate metal fasteners.',
      warranty_info: '2-year structural warranty against manufacturing defects.',
      support_email: 'support@oakandroom.com',
      target_markets: ['EU', 'UK'],
      last_updated: new Date().toISOString().split('T')[0],
      eudr_watch_notes: 'European oak sourced from FSC-certified Lithuanian forests. EUDR traceability data available from supplier.',
      gpsr_notes: 'Safety and load capacity information provided.',
      dpp_readiness_notes: 'Core DPP fields completed. EUDR watch flag added for wood.',
    },
  },
  {
    id: 'ceramic-mug',
    label: 'Ceramic Mug',
    description: 'A homeware product with material safety and care information.',
    data: {
      ...EMPTY_PASSPORT,
      brand_name: 'Clay House',
      product_name: 'Handmade Ceramic Mug',
      category: 'Homeware',
      product_type: 'Mug',
      sku: 'CH-MUG-SC-001',
      model: 'Studio Classic Mug',
      product_category_module: 'homeware',
      materials: 'Stoneware clay, food-safe glaze',
      composition: 'Body: stoneware clay. Glaze: food-safe ceramic glaze (lead and cadmium free).',
      country_of_origin: 'Portugal',
      production_country: 'Portugal',
      manufacturer_name: 'Olaria do Alentejo',
      manufacturer_contact: 'hello@clayhousestudio.com',
      care_instructions: 'Dishwasher safe. Microwave safe. Avoid thermal shock (do not pour boiling water into a cold mug).',
      safety_warnings: 'Check for cracks before use. Do not use if cracked or chipped.',
      repair_info: 'Ceramics cannot be repaired for food use if cracked.',
      recycling_info: 'Ceramics recycling available in some areas. Check local guidelines.',
      warranty_info: 'Defects on arrival only. Contact within 7 days of delivery.',
      support_email: 'hello@clayhousestudio.com',
      target_markets: ['EU', 'UK'],
      last_updated: new Date().toISOString().split('T')[0],
      gpsr_notes: 'Food-safe certification available. Lead and cadmium free glaze.',
    },
  },
  {
    id: 'linen-pillow',
    label: 'Home Textile Pillow Cover',
    description: 'A home textile with composition and care labelling data.',
    data: {
      ...EMPTY_PASSPORT,
      brand_name: 'Soft Loom',
      product_name: 'Linen Pillow Cover',
      category: 'Home textile',
      product_type: 'Pillow cover',
      sku: 'SL-PIL-LN-001',
      model: 'Classic Linen Cover',
      product_category_module: 'textile',
      materials: '100% European linen (flax)',
      composition: '100% linen',
      recycled_content: 'Not applicable (virgin linen)',
      packaging_materials: 'Recycled cardboard sleeve',
      country_of_origin: 'Lithuania',
      production_country: 'Lithuania',
      manufacturer_name: 'Linas Audimas UAB',
      manufacturer_contact: 'orders@softloom.com',
      care_instructions: 'Machine wash cold (30°C). Tumble dry low. Iron on low. Linen softens with each wash.',
      safety_warnings: 'Keep away from open flame. Decorative use — not for children under 3 years.',
      repair_info: 'Seam repair possible with matching thread.',
      recycling_info: 'Textile recycling available. Remove zipper if present.',
      warranty_info: '30-day defect policy.',
      support_email: 'care@softloom.com',
      target_markets: ['EU', 'UK'],
      last_updated: new Date().toISOString().split('T')[0],
      textile_label_notes: 'Fibre composition: 100% linen. Care labels sewn in.',
      gpsr_notes: 'Manufacturer information provided.',
    },
  },
];
