import type { PassportRecord } from './types';
import { EMPTY_PASSPORT } from './types';

// ============================================================
// Sample Passport Templates
// Realistic demo data for customer demonstrations.
// ============================================================

export interface SampleTemplate {
  id: string;
  label: string;
  description: string;
  data: Omit<PassportRecord, 'slug' | 'edit_token'>;
}

export const SAMPLE_TEMPLATES: SampleTemplate[] = [
  {
    id: 'organic-cotton-tee',
    label: 'Organic Cotton T-Shirt',
    description: 'A textile product with full composition, care, safety, and sustainability data.',
    data: {
      ...EMPTY_PASSPORT,
      brand_name: 'Loom & Field',
      product_name: 'Organic Cotton Everyday Tee',
      category: 'Textile / apparel',
      product_type: 'T-shirt',
      sku: 'LF-TEE-OC-001',
      model: 'Everyday Tee',
      batch_number: 'B2026-Q1-004',
      gtin: '4012345678901',
      product_page_url: 'https://loomandfield.com/products/organic-everyday-tee',
      product_category_module: 'textile',
      materials: '100% organic cotton jersey, GOTS certified. Mid-weight 180gsm fabric with a soft, brushed interior. Natural off-white colour achieved without bleaching.',
      composition: '100% organic cotton (Gossypium hirsutum)',
      recycled_content: 'Not applicable (organic virgin cotton)',
      packaging_materials: 'Recycled paper mailer (80% post-consumer), compostable corn-starch poly bag',
      country_of_origin: 'Portugal',
      production_country: 'Portugal',
      supplier_name: 'Fios do Norte SA',
      manufacturer_name: 'Fábrica Têxtil do Norte, Lda.',
      manufacturer_contact: 'info@loomandfield.com | +351 252 000 000',
      responsible_person_contact: 'Loom & Field GmbH, Schönhauser Allee 12, 10119 Berlin, Germany',
      care_instructions: 'Machine wash cold (30°C). Do not bleach. Line dry preferred. Iron on low heat if needed. Do not dry clean.',
      instructions_for_use: 'Wear as casual or layering piece. Pre-washed to minimise shrinkage.',
      safety_warnings: 'Keep away from open flame. Fabric may be flammable.',
      repair_info: 'Small holes can be repaired with cotton thread and a simple darning stitch. Repair guide available at loomandfield.com/repair.',
      recycling_info: 'Textile recycling available in most EU countries. Remove all labels and trims before recycling. Pure cotton is compostable under industrial conditions.',
      end_of_life_info: 'When worn out: reuse as cleaning cloth, donate, or recycle through textile collection points.',
      takeback_info: 'Send to Loom & Field Circular Program for recycling credit. Free return shipping within EU.',
      warranty_info: '30-day return policy for manufacturing defects. Covers seam failure, colour defects, and sizing errors.',
      support_email: 'hello@loomandfield.com',
      support_url: 'https://loomandfield.com/support',
      target_markets: ['EU', 'UK'],
      last_updated: new Date().toISOString().split('T')[0],
      textile_label_notes: 'Fibre composition: 100% organic cotton. Care labels sewn in according to EU Textile Regulation 1007/2011.',
      gpsr_notes: 'Manufacturer and responsible person information provided. Product safety and flammability information included. No known chemical hazards.',
      dpp_readiness_notes: 'Core DPP fields completed for textile product. Composition, origin, care, repairability, and recyclability data included.',
      reach_svhc_notes: 'No SVHC substances above 0.1% w/w. GOTS certification covers restricted substances list.',
      packaging_ppwr_notes: 'Packaging is 80% recycled paper and compostable bio-plastic. Total packaging weight: 15g.',
    },
  },
  {
    id: 'leather-bag',
    label: 'Handmade Leather Bag',
    description: 'A leather goods product with material sourcing, EUDR watch notes, and care information.',
    data: {
      ...EMPTY_PASSPORT,
      brand_name: 'Atelier North',
      product_name: 'Handmade Leather Crossbody Bag',
      category: 'Leather goods / accessories',
      product_type: 'Crossbody bag',
      sku: 'AN-BAG-CB-001',
      model: 'Crossbody Classic',
      batch_number: 'AN-2026-015',
      product_page_url: 'https://ateliernorth.com/products/crossbody-classic',
      product_category_module: 'leather_goods',
      materials: 'Vegetable-tanned full-grain bovine leather (1.2mm thickness), cotton twill lining (unbleached), solid brass hardware (buckles, rivets, D-rings)',
      composition: 'Exterior: 100% bovine leather (vegetable-tanned). Lining: 100% cotton twill. Hardware: solid brass (lacquered).',
      substances_of_concern: 'Chrome-free tanning process. No PFC/PFAS used in water-resistance treatment.',
      country_of_origin: 'Spain',
      production_country: 'Spain',
      supplier_name: 'Tenería del Sur SA (Ubrique, Spain)',
      manufacturer_name: 'Taller Artesano de Ubrique',
      manufacturer_contact: 'contact@ateliernorth.com | +34 956 000 000',
      responsible_person_contact: 'Atelier North ApS, Vesterbrogade 47, 1620 Copenhagen, Denmark',
      care_instructions: 'Wipe with a soft dry cloth after use. Condition leather with natural beeswax conditioner every 3–6 months. Store in dust bag when not in use. Avoid prolonged direct sunlight and moisture.',
      safety_warnings: 'Avoid prolonged moisture exposure — leather may stain. Metal hardware may cause skin reaction in people with nickel sensitivity (hardware is nickel-free). Not intended for children under 3.',
      repair_info: 'Strap replacement and hardware repair available through brand workshop. Contact for repair booking form. Average repair turnaround: 2–3 weeks within EU.',
      spare_parts_info: 'Replacement straps, buckles, and D-rings available. Contact support for parts ordering.',
      durability_notes: 'Full-grain leather develops a natural patina over time. Designed for 5+ years of daily use with proper care.',
      recycling_info: 'Separate metal hardware before recycling leather. Leather can be composted under industrial conditions. Brass hardware is infinitely recyclable.',
      end_of_life_info: 'Return to brand for refurbishment or responsible disposal. Leather scraps can be donated to leather crafting communities.',
      warranty_info: '1-year workmanship warranty covering structural defects, stitching failure, and hardware malfunction. Does not cover normal wear, patina, or accidental damage.',
      support_email: 'care@ateliernorth.com',
      support_url: 'https://ateliernorth.com/care',
      target_markets: ['EU', 'UK', 'US'],
      last_updated: new Date().toISOString().split('T')[0],
      eudr_watch_notes: 'Bovine leather sourced from EU-based tannery (Ubrique, Spain). Cattle supply chain traceable to EU farms. Monitor EUDR regulatory changes for cattle-derived products. Supplier traceability documentation on file.',
      gpsr_notes: 'Manufacturer information and responsible person contact provided. Product does not contain known chemical hazards. Chrome-free tanning verified.',
      dpp_readiness_notes: 'Core DPP fields completed. EUDR watch flag added for bovine leather. Material origin, repairability, and end-of-life information included.',
      reach_svhc_notes: 'Chrome-free tanning process. Supplier declaration for restricted substances on file.',
    },
  },
  {
    id: 'wooden-stool',
    label: 'Wooden Stool',
    description: 'A furniture product with wood traceability, FSC certification, and EUDR watch notes.',
    data: {
      ...EMPTY_PASSPORT,
      brand_name: 'Oak & Room',
      product_name: 'Solid Oak Utility Stool',
      category: 'Furniture / wood',
      product_type: 'Stool',
      sku: 'OR-STL-OAK-001',
      model: 'Utility Stool',
      batch_number: 'OR-2026-S03',
      serial_number: 'OR-2026-S03-0042',
      product_page_url: 'https://oakandroom.com/products/utility-stool',
      product_category_module: 'furniture',
      materials: 'Solid European oak (Quercus robur), FSC-certified. Water-based polyurethane lacquer finish (VOC-free). Stainless steel wood screws (hidden).',
      composition: 'Frame and seat: 100% European oak. Finish: water-based lacquer (VOC-free). Fasteners: stainless steel.',
      recycled_content: 'Wood is sourced from managed forests (virgin material). Packaging uses 100% recycled cardboard.',
      packaging_materials: '100% recycled corrugated cardboard box, recycled paper padding. No plastic packaging.',
      country_of_origin: 'Lithuania',
      production_country: 'Lithuania',
      supplier_name: 'Lietuvos Mediena UAB (Lithuanian timber)',
      manufacturer_name: 'Medžio Dirbtuvės UAB',
      manufacturer_contact: 'hello@oakandroom.com | +370 5 000 0000',
      responsible_person_contact: 'Oak & Room GmbH, Friedrichstraße 123, 10117 Berlin, Germany',
      care_instructions: 'Wipe with a slightly damp cloth. Dry immediately. Avoid standing water and hot objects directly on surface. Do not use abrasive or chemical cleaners. Re-oil or re-lacquer every 2–3 years for best appearance.',
      instructions_for_use: 'Indoor use only. Place on level, stable surface. Do not stand on the seat. Assembly: no assembly required — arrives fully assembled.',
      safety_warnings: 'Indoor use only. Maximum load capacity: 120kg. Place on level surface to prevent tipping. Not intended as a step stool. Keep away from heat sources.',
      foreseeable_misuse: 'Standing on the stool, using as a step ladder, outdoor use, exceeding weight limit.',
      repair_info: 'Minor surface damage: sand lightly with 220-grit sandpaper and apply matching lacquer. For structural damage, contact brand workshop for professional repair.',
      spare_parts_info: 'Replacement legs and seat available individually. Matching lacquer touch-up kit available. Contact support for parts ordering.',
      durability_notes: 'Solid oak construction designed for 10+ years of daily use with proper care. Wood naturally hardens and develops character over time.',
      recycling_info: 'Wood is recyclable or reusable. Separate stainless steel fasteners before recycling. Oak wood can be chipped for biomass or composting.',
      end_of_life_info: 'Return to brand buyback program for refurbishment. Alternatively, donate, repurpose, or recycle wood and metal components separately.',
      takeback_info: 'Oak & Room offers a buyback credit for returned furniture in good structural condition.',
      warranty_info: '2-year structural warranty against manufacturing defects (includes joints, legs, seat). Does not cover cosmetic wear, scratches, or damage from improper use.',
      support_email: 'support@oakandroom.com',
      support_url: 'https://oakandroom.com/support',
      target_markets: ['EU', 'UK'],
      last_updated: new Date().toISOString().split('T')[0],
      eudr_watch_notes: 'European oak (Quercus robur) sourced from FSC-certified Lithuanian forests. EUDR traceability data and geolocation coordinates available from timber supplier (Lietuvos Mediena UAB). Due diligence documentation on file.',
      gpsr_notes: 'Safety information, load capacity, and intended use provided. Manufacturer and responsible person contact details included. No known chemical hazards in finished product.',
      dpp_readiness_notes: 'Core DPP fields completed for furniture product. EUDR watch flag added for wood/timber. Material origin, repairability, durability, and end-of-life information fully documented.',
      reach_svhc_notes: 'VOC-free water-based lacquer. No SVHC substances above 0.1% w/w in finished product.',
      packaging_ppwr_notes: 'Packaging is 100% recycled corrugated cardboard. No plastic components. Packaging weight: approximately 450g.',
    },
  },
  {
    id: 'ceramic-mug',
    label: 'Ceramic Mug',
    description: 'A homeware product with material safety, food-contact compliance, and care information.',
    data: {
      ...EMPTY_PASSPORT,
      brand_name: 'Clay House',
      product_name: 'Handmade Ceramic Mug',
      category: 'Homeware',
      product_type: 'Mug',
      sku: 'CH-MUG-SC-001',
      model: 'Studio Classic Mug',
      batch_number: 'CH-2026-B07',
      product_page_url: 'https://clayhousestudio.com/products/studio-classic-mug',
      product_category_module: 'homeware',
      materials: 'Stoneware clay (fired at 1250°C), food-safe glaze (lead-free, cadmium-free). Each piece is individually hand-thrown.',
      composition: 'Body: stoneware clay. Glaze: food-safe ceramic glaze (lead-free, cadmium-free). Capacity: approximately 350ml.',
      packaging_materials: 'Recycled cardboard box with recycled tissue paper. Biodegradable foam insert.',
      country_of_origin: 'Portugal',
      production_country: 'Portugal',
      supplier_name: 'Argilas do Alentejo Lda.',
      manufacturer_name: 'Olaria do Alentejo',
      manufacturer_contact: 'hello@clayhousestudio.com | +351 266 000 000',
      responsible_person_contact: 'Clay House Studio Ltd, 42 Brick Lane, London E1 6RF, United Kingdom',
      care_instructions: 'Dishwasher safe (top rack recommended). Microwave safe. Avoid thermal shock — do not pour boiling water into a cold mug straight from the fridge. Hand-wash with soft sponge for best longevity.',
      instructions_for_use: 'Suitable for hot and cold beverages. Not suitable for oven or stovetop use.',
      safety_warnings: 'Check for cracks or chips before each use. Do not use if cracked, chipped, or damaged — sharp edges may cause injury. Handle may be hot when filled with hot liquid.',
      age_warning: 'Not suitable for children under 3 years due to breakage risk.',
      repair_info: 'Ceramics cannot be safely repaired for food use once cracked or chipped. Broken pieces can be used for mosaic art or garden drainage.',
      recycling_info: 'Ceramics cannot be recycled through standard glass/bottle recycling. Check local guidelines for ceramics disposal. Broken stoneware is inert and can be used as garden aggregate.',
      end_of_life_info: 'Repurpose as plant pot, pen holder, or garden decoration. Stoneware is chemically inert and will not leach into soil.',
      warranty_info: 'Arrival condition guarantee: contact within 7 days of delivery for breakage during shipping. Does not cover drops, chips, or thermal shock damage.',
      support_email: 'hello@clayhousestudio.com',
      support_url: 'https://clayhousestudio.com/contact',
      target_markets: ['EU', 'UK'],
      last_updated: new Date().toISOString().split('T')[0],
      gpsr_notes: 'Food-safe certification available on request. Lead-free and cadmium-free glaze verified by independent laboratory testing (EU food contact regulation EC 1935/2004). Manufacturer and responsible person contact information provided.',
      dpp_readiness_notes: 'Core transparency fields completed for homeware product. Food-contact safety information included.',
      reach_svhc_notes: 'Stoneware and glaze contain no SVHC substances. Lead-free and cadmium-free.',
    },
  },
  {
    id: 'linen-pillow',
    label: 'Home Textile Pillow Cover',
    description: 'A home textile with full fibre composition, care labelling, and packaging data.',
    data: {
      ...EMPTY_PASSPORT,
      brand_name: 'Soft Loom',
      product_name: 'Linen Pillow Cover',
      category: 'Home textile',
      product_type: 'Pillow cover',
      sku: 'SL-PIL-LN-001',
      model: 'Classic Linen Cover',
      batch_number: 'SL-2026-P03',
      gtin: '4012345678918',
      product_page_url: 'https://softloom.com/products/linen-pillow-cover',
      product_category_module: 'textile',
      materials: '100% European linen (flax, Linum usitatissimum). Stonewashed finish for softness. Hidden zipper closure (YKK brass zipper). Available in Natural, Oatmeal, and Sage.',
      composition: '100% linen (flax)',
      recycled_content: 'Not applicable (virgin linen)',
      packaging_materials: 'Recycled cardboard sleeve with soy-based ink printing. No plastic packaging.',
      country_of_origin: 'Lithuania',
      production_country: 'Lithuania',
      supplier_name: 'Linų Audiniai UAB',
      manufacturer_name: 'Linas Audimas UAB',
      manufacturer_contact: 'orders@softloom.com | +370 5 000 0001',
      responsible_person_contact: 'Soft Loom BV, Herengracht 88, 1015 BS Amsterdam, Netherlands',
      care_instructions: 'Machine wash cold (30°C) with like colours. Tumble dry on low heat. Iron on medium-low while slightly damp. Linen naturally softens and gains character with each wash. Do not bleach.',
      instructions_for_use: 'Fits standard European pillow 50×70cm. Insert pillow through hidden side zipper.',
      safety_warnings: 'Keep away from open flame — linen is flammable. Decorative use — not suitable as a toy for children under 3 years (strangulation hazard from zipper).',
      repair_info: 'Seam repair possible with matching linen thread. Zipper replacement available through brand — contact support.',
      recycling_info: 'Pure linen is biodegradable and compostable. Remove metal zipper before recycling through textile collection. Linen can be industrially composted.',
      end_of_life_info: 'Donate if in good condition. Compost (remove zipper) or recycle through textile collection points.',
      warranty_info: '30-day manufacturing defect policy covering stitching errors, colour defects, and zipper malfunction.',
      support_email: 'care@softloom.com',
      support_url: 'https://softloom.com/support',
      target_markets: ['EU', 'UK'],
      last_updated: new Date().toISOString().split('T')[0],
      textile_label_notes: 'Fibre composition: 100% linen. Care labels sewn in per EU Textile Regulation 1007/2011. Country of manufacture: Lithuania.',
      gpsr_notes: 'Manufacturer and responsible person contact information provided. Flammability and child safety warnings included.',
      dpp_readiness_notes: 'Core DPP fields completed for home textile product. Composition, care, repairability, and recyclability data documented.',
      reach_svhc_notes: 'OEKO-TEX Standard 100 certified (Class II). No harmful substances detected.',
      packaging_ppwr_notes: 'Packaging is 100% recycled cardboard with soy-based inks. No plastic. Packaging weight: 20g.',
    },
  },
];
