-- PassportKit optional local/dev seed data.
-- Do not run this in production unless you intentionally want demo content.

insert into passports (
  slug,
  edit_token,
  brand_name,
  product_name,
  category,
  product_type,
  sku,
  materials,
  composition,
  country_of_origin,
  production_country,
  manufacturer_name,
  manufacturer_contact,
  care_instructions,
  safety_warnings,
  repair_info,
  recycling_info,
  warranty_info,
  support_email,
  target_markets,
  product_category_module,
  data_quality_score,
  readiness_level,
  status,
  visibility,
  watermark,
  last_updated,
  source,
  plan_snapshot
)
values (
  'demo-organic-tee',
  'dev-edit-token-replace-before-sharing',
  'Loom & Field',
  'Organic Cotton Everyday Tee',
  'Textile / apparel',
  'T-shirt',
  'LF-TEE-DEV',
  '100% organic cotton jersey',
  '100% organic cotton',
  'Portugal',
  'Portugal',
  'Demo Textile Studio',
  'compliance@example.com',
  'Machine wash cold. Line dry.',
  'Keep away from open flame.',
  'Small holes can be repaired with cotton thread.',
  'Recycle through textile collection where available.',
  '30-day manufacturing defect policy.',
  'support@example.com',
  array['EU', 'UK'],
  'textile',
  86,
  'strong',
  'published',
  'public',
  true,
  current_date,
  'manual',
  'free'
)
on conflict (slug) do nothing;
